#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
CWD=$PWD
cd $DIR
mkdir -p /etc/dhd
echo 22 > /etc/dhd/port
echo 30 > /etc/dhd/maxage
echo localhost > /etc/dhd/server
cat dhd.sh > /usr/bin/dhd
cat dhd-dial.init > /etc/init.d/dhd-dial
chmod +x /usr/bin/dhd
chmod +x /etc/init.d/dhd-dial
cd $CWD